### ISSUE TITLE
Do not unwrap

### ISSUE THREAD

**Issue by svenstaro** [mmrath/serde_type_name#1]
Hi, this is a useful little library. However, its use is diminished quite a bit by the fact that you use unwrap like this: `t.serialize(TypeName).unwrap()`. The problem with this is that now I can't catch thrown errors. Could you change it to return a proper `Result` instead?

**Comment by mmrath** [comment]
I just changed the signature and released 0.2.0 to crates.io. Please can you see if it looks ok now?

**Comment by svenstaro** [comment]
That works perfectly for my purposes, thanks! Keep up the good work.
